Formatting: Use black for formatting.
Far from great, but it takes away silly decisions from us.

diff --git a/scripts/git/hooks/pre-commit b/scripts/git/hooks/pre-commit
--- a/scripts/git/hooks/pre-commit
+++ b/scripts/git/hooks/pre-commit
@@ -32,13 +32,20 @@ if [ -n "$touched_python_files" ]; then
     fi
 fi
 
+if black --check .
+then
+	  echo "Formatting passed"
+else
+	  echo "Formatting failed."
+	  exit 1
+fi
 
 if pytest
 then
 	  echo "Tests passed"
 else
 	  echo "Tests failed. Aborting commit."
-	  exit 1
+	  exit 2
 fi
 
 if ./main.py
@@ -46,5 +53,5 @@ then
 	  echo "Main runs"
 else
 	  echo "Main failed. Aborting commit."
-	  exit 2
+	  exit 3
 fi
